name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java 11
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Download and extract Apache JMeter
      - name: Download Apache JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH



      # Ensure reports directory exists
      - name: Create Reports Directory
        run: mkdir -p reports

      # Run the JMeter test
      - name: Run JMeter Test
        run: |
          jmeter -n -t tests/Login_Demo.jmx -l reports/results.jtl -j reports/jmeter.log -Jsummariser.name=none

      # Generate HTML report
      - name: Generate HTML Report
        run: |
          jmeter -g reports/results.jtl -o reports/html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: reports/html 


      - name: Commit JMeter HTML Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/html
          git commit -m "Update JMeter HTML report [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
