name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Apache JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: Run JMeter Test
        run: |
          jmeter -n -t tests/Login_Demo.jmx -l reports/results.jtl -j reports/jmeter.log

      - name: Generate HTML Report
        run: |
          jmeter -g reports/results.jtl -o reports/html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: reports/html
