name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java 11
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Required input
          java-version: '11'

      # Download and extract Apache JMeter
      - name: Download Apache JMeter
        run: |
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          echo "$PWD/apache-jmeter-5.6.2/bin" >> $GITHUB_PATH

      # Ensure reports directory exists
      - name: Create Reports Directory
        run: mkdir -p reports

      # Run the JMeter test
      - name: Run JMeter Test
        run: |
          jmeter -n -t tests/Login_Demo.jmx -l reports/results.jtl -j reports/jmeter.log

      # Generate HTML report
      - name: Generate HTML Report
        run: |
          jmeter -g reports/results.jtl -o reports/html

      # Upload the HTML report as an artifact
      - name: Upload T
